name = "SemanticFlowGraphs"
uuid = "ce4a9274-ad72-11e8-1140-c9a2f4ff8ac8"
license = "Apache2"
authors = ["Evan Patterson <evan@epatters.org>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Serd = "42699a24-3520-5f41-a549-6a478ed667c2"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Catlab = "0.14"
Serd = "0.3"
StructEquality = "^2"
julia = "1.6"
